### ISSUE TITLE
kapag na plot na last subject na pipindot parin create 

### ISSUE THREAD

**Issue by moyaliachem** [xtrajosh/ThesisRepo#5]
![error101](https://user-images.githubusercontent.com/41364040/52037680-095bf900-2573-11e9-97da-8f2d0243c984.png)

**Comment by xtrajosh** [comment]
Create Button now disables whenever there is no more subject to plot in the current semester. I also secured the button by disabling it when plotted schedule want to be changed. This issue seems to be resolved.
