### ISSUE TITLE
Kapag plinot nasasama yung vacant sa kulay

### ISSUE THREAD

**Issue by moyaliachem** [xtrajosh/ThesisRepo#6]
ginawa ko kasi plinot ko muna yung lect sa 7am-9am tapos plinot ko lab sa 10pm-1pm edi may vacant na 1hour 9am-10am (bawal ma create to kasi nauna lect sinandya ko talaga unahin lect) tapos ginawa ko binaliktad ko na plinot ko ulit to same subject pero yung 7am-10pm ginawa ko na siya lab tapos 10am-11am vacant tapos 11am-1pm lect kapag nicreate mo yan mangyayare yang sa picture
![51080268_293288131541604_3425559284136542208_n](https://user-images.githubusercontent.com/41364040/52038889-7de46700-2576-11e9-93a4-fc115055a518.png)

**Comment by xtrajosh** [comment]
Having the list inside of the plotting event is not resetted when there will be another plot. This is issue is resolved.
