### ISSUE TITLE
Not same cell plotted on lect and lab (Faculty Member Button and Room)

### ISSUE THREAD

**Issue by moyaliachem** [xtrajosh/ThesisRepo#8]
### **first plotted schedule na plinot nagiging ganyan lect or lab basta kung sino na una sa dalawa  nababawasan ng isang cell palagi**
![image](https://user-images.githubusercontent.com/41364040/52115810-80b08c00-264a-11e9-8ab1-1f13af44ec58.png)

**Comment by xtrajosh** [comment]
Appears to happen that every time the method LoadSchedz() happens, the plotted schedule for that subject will refresh and will decrement 1 cell everytime. Still ongoing.
